name: build-photon-app

on:
  push:
    branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  execute:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/setup-node@v4
      with:
          node-version: lts/*
  
    - name: Install Node Dependencies
      run: npm i
    
    - name: Build Windows App
      run: npm run tauri build 

    - name: Get App Build Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/src-tauri/target/release/bundle/msi/*.msi"
        bodyFile: "README.md"
        tag: photon v${{ steps.package-version.outputs.current-version}}
