name: build-photon-app

on:
  push:
    branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  execute:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/setup-node@v4
      with:
          node-version: lts/*
  
    - name: Install Node Dependencies
      run: npm i
    
    - name: Build Windows App
      run: npm run tauri build 

    - name: Get Build Version
      id: package-version
      shell: pwsh
      run: |
        # Extract version from package.json using npm, remove quotes
        $version = npm pkg get version --ws=false | ConvertFrom-Json
        # Set environment variable for subsequent steps
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/src-tauri/target/release/bundle/msi/*.msi"
        bodyFile: "README.md"
        tag: "photon-v${{ env.APP_VERSION}}"
